### PR TITLE
Submission edits

### PR DESCRIPTION
**Pull request by gabrieldansereau**
Final edits before submission. Tim mentioned we have to update the style of figure 5, re-read, make sure the labels all have the same size, and we can submit (in #15). We also have to finish a few things to meet submission requirements (#16). 

There are also a few things left in the ROADMAP (#1), as well as a some opened issues. Might be good to address and close these.

### CODE REVIEW

**Comment by tpoisot** [comment]
We might also want to re-assess the order of authors - seems like @gabrieldansereau is taking the lead, and it's important that we have this discussion. I can't easily evaluate the amount of work done by the three of you during the class, but we want to make sure that the order of authors is correct. Let's have a brief talk about it _in person_ later this week.

**Comment by tpoisot** [comment]
Est-ce que tout est OK de ton côté @gabdansereau? Si oui, je vais relire et faire les dernières modifications si nécessaire.

**Comment by gabrieldansereau** [comment]
Presque! J'allais ouvrir une issue pour un élément sur lequel je voulais avoir ton avis. Sinon, je vais ouvrir une nouvelle pull-request pour les contributions des auteurs. Je te mentionne quand c'est fait.

**Comment by gabrieldansereau** [comment]
Merging this into master. I'll open a new pull-request for author contributions and final changes.

**Pull request merged**
